name: Update Submodule

# on:
#   release:
#     types: [published]

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kakarot-RPC Repository
        uses: actions/checkout@v4
        with:
          repository: kkrt-labs/kakarot-rpc
          token: ${{ secrets.GITHUB_TOKEN }}
          path: kakarot-rpc

      - name: Update Submodule
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd kakarot-rpc/lib/kakarot
          echo "Current directory: $(pwd)"
          git fetch --tags
          export release_tag=$(git tag --sort=-creatordate | head -n 1)
          git checkout $release_tag
          cd ../..
          git checkout -b kakarot-$release_tag
          git add lib/kakarot
          git commit -m "Update kakarot to $release_tag"
          gh pr create -B main -H kakarot-$release_tag --title 'Update Kakarot to $release_tag'
          cd -
